language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

before_install:
  - git submodule foreach git pull origin master

# command to install dependencies
install:
  - python setup.py build_ext
# command to run tests
script:
#  - pytest
  - python -m nose2